"""Deprecation of the per-processor ``axis`` setting.

A processor that carries state *between* messages -- filter initial conditions,
a running mean, a sample buffer, a previous-sample cache -- can only do so along
the dimension messages accumulate along. Carrying it along a static axis is not
a smaller error but a different operation: that axis has the same length every
message, so the carried state applies message N's tail to message N+1's head at
the same coordinate, forever.

Which dimension that is belongs to the producer, and
:attr:`~ezmsg.util.messages.axisarray.AxisArray.chunk_dim` is where it says so.
A setting that lets a consumer disagree can only be used to be wrong, so it is
going away; see :func:`~ezmsg.sigproc.util.message.resolve_chunk_dim`.

During the deprecation window the setting is still honoured, so nothing changes
behaviour until it is removed. Two warnings partition the call sites:

* This module's construction-time :class:`FutureWarning` fires for *every* use,
  including a harmless ``axis="time"`` on a raw stream. It means "delete this".
* :func:`~ezmsg.sigproc.util.message.resolve_configured_chunk_dim`'s runtime
  warning fires only when the configured axis disagrees with a *declared*
  ``chunk_dim``. It means "deleting this will change what this stage computes".

To find every remaining call site in a pipeline, run its tests with
``-W error::FutureWarning``.
"""

import sys
import typing
import warnings
from contextlib import contextmanager
from contextvars import ContextVar

__all__ = [
    "AXIS_REMOVAL_VERSION",
    "suppress_axis_deprecation",
    "warn_axis_deprecated",
]

AXIS_REMOVAL_VERSION = "4.0"
"""Release that drops the deprecated ``axis`` settings. Deprecated in 3.8."""

_suppressed: ContextVar[bool] = ContextVar("_axis_deprecation_suppressed", default=False)


@contextmanager
def suppress_axis_deprecation() -> typing.Iterator[None]:
    """Silence the construction-time warning while forwarding a setting internally.

    A stage that builds a child processor from its own already-warned settings
    (:obj:`~ezmsg.sigproc.scaler.AdaptiveStandardScalerTransformer` and its two
    EWMAs, :obj:`~ezmsg.sigproc.decimate.Decimate` and its anti-alias filter)
    would otherwise warn a second time for one user-visible setting -- and, since
    some of that forwarding happens in ``_reset_state``, would warn mid-stream
    pointing at whatever is driving the pipeline rather than at any call site.

    Deleted along with the settings themselves; see :data:`AXIS_REMOVAL_VERSION`.
    """
    token = _suppressed.set(True)
    try:
        yield
    finally:
        _suppressed.reset(token)


def _user_stacklevel() -> int:
    """``stacklevel`` that makes a ``warn()`` in this module's caller point at
    the first frame outside ezmsg.

    A fixed level cannot work: the depth differs between
    ``WindowSettings(axis=...)`` (the dataclass ``__init__``) and
    ``Window(axis=...)`` (through ``_unify_settings``), and the functional
    factories build the settings object inside this package, so a fixed level
    would blame ``scaler.py`` for a call the user made.
    """
    # Frames are identified by module rather than by filename. The dataclass
    # __init__ every one of these settings objects is constructed through is
    # generated by exec, so its co_filename is "<string>" -- indistinguishable
    # from a user running `python -c`. Its globals, though, are the defining
    # module's, so f_globals says "ezmsg.sigproc.window" and the walk continues
    # correctly in both cases.
    #
    # 0 is this function, 1 is warn_axis_deprecated -- the frame a stacklevel of
    # 1 would name. Walk out from there until we leave the package.
    frame: typing.Any = sys._getframe(1)
    level = 1
    while frame is not None:
        module = frame.f_globals.get("__name__", "")
        if module != "ezmsg" and not module.startswith("ezmsg."):
            return level
        if frame.f_back is None:
            # Never left the package (a settings object built at import time, or
            # from a bare exec). Blaming the outermost frame beats pointing the
            # user at `sys:1`.
            return level
        frame = frame.f_back
        level += 1
    return level


def warn_axis_deprecated(settings: typing.Any, field: str = "axis") -> None:
    """Warn that *settings*' ``field`` is deprecated, if it was actually set.

    Call from a ``__post_init__``: ``ez.Settings`` classes are frozen dataclasses
    and every construction path -- the settings class, the transformer, the unit,
    and the functional factory -- funnels through their ``__init__``, so one hook
    covers all four.
    """
    if getattr(settings, field, None) is None or _suppressed.get():
        return
    warnings.warn(
        f"{type(settings).__name__}.{field} is deprecated and will be removed in "
        f"ezmsg-sigproc {AXIS_REMOVAL_VERSION}. This processor carries state between "
        f"messages, which is only meaningful along the dimension they accumulate "
        f"along; that dimension now comes from AxisArray.chunk_dim. Drop the setting. "
        f"If the stream's chunk_dim is wrong, fix it at the producer.",
        FutureWarning,
        stacklevel=_user_stacklevel(),
    )
